#ifndef _OCEAN_DESCRIPTION_H_
#define _OCEAN_DESCRIPTION_H_

enum
{
	OD_OCEAN_DESCRIPTION = 1000,
	
	OD_OCEAN_RESOLUTION = 10000,
	OD_OCEAN_SIZE,
	OD_WIND_SPEED,
	OD_WIND_DIRECTION,
	OD_SHRT_WAVELENGHT,
	OD_WAVE_HEIGHT,
	OD_SEED,
	OD_CHOPAMOUNT,
	OD_DAMP_REFLECT,
	OD_WIND_ALIGNMENT,
	OD_OCEAN_DEPTH,
	OD_CURRENTTIME,
	OD_TIMELOOP,
	OD_TIMESCALE,
	OD_AUTO_ANIM_TIME,
	OD_DO_CHOPYNESS,
	OD_DO_CATMU_INTER,
	OD_DO_NORMALS,
	OD_DO_JACOBIAN,
	OD_JACOBMAP,
	OD_ID_GRP_FOAM,
	OD_FOAMMAP,
	OD_PRE_RUN_FOAM,
	OD_JACOB_THRES,
	OD_FOAM_THRES,
	OD_PSEL_PARTICLES,
	OD_PSEL_THRES,
	OD_ACTIVE_DEFORM,
	OD_CREATE_FOAM_TAGS,

	// for the cycle, create power of 2
	OD_RESO_4 =4,
	OD_RESO_5 =5,
	OD_RESO_6 =6,
	OD_RESO_7 =7,
	OD_RESO_8 =8,
	OD_RESO_9 =9,
	OD_RESO_10 =10,
	OD_RESO_11 = 11,
	OD_RESO_12 = 12,
	OD_RESO_13 = 13,
	OD_RESO_14 = 14
};

#endif